name: ally_care_demo
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.8

  # Environment & Network
  flutter_dotenv: ^5.2.1
  dio: ^5.8.0+1
  connectivity_plus: ^6.1.4

  # State Management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.3.3

  # Firebase
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  cloud_firestore: ^5.6.11
  firebase_storage: ^12.4.9

  # Navigation
  go_router: ^12.1.3

  # Google Sign In
  google_sign_in: ^6.2.1

  # Local Storage
  shared_preferences: ^2.5.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # UI & Animations
  shimmer: ^3.0.0
  lottie: ^2.7.0

  # Refresh & Calendar
  pull_to_refresh: ^2.0.0
  table_calendar: ^3.2.0

  # Image handling
  image_picker: ^1.0.4
  cached_network_image: ^3.4.1

  # Typography & Responsive
  google_fonts: ^6.1.0
  flutter_screenutil: ^5.9.0

  # Utilities
  dartz: ^0.10.1
  equatable: ^2.0.5
  uuid: ^4.3.3
  intl: ^0.20.2

  # Localization
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.2.0
  animations: ^2.0.11
  sliver_snap: ^2.1.1
  animated_icon: ^0.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.3.3

  # Code Generation
  riverpod_generator: ^2.3.9
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true
  generate: true  # For localization

  assets:
    - assets/images/
    - assets/images/logo/
    - assets/images/logo/company_logo.svg
    - assets/images/icons/
    - assets/images/illustrations/
    - assets/animations/
    - .env
#
#  fonts:
#    - family: Poppins
#      fonts:
#        - asset: assets/fonts/Poppins-Regular.ttf
#        - asset: assets/fonts/Poppins-Medium.ttf
#          weight: 500
#        - asset: assets/fonts/Poppins-SemiBold.ttf
#          weight: 600
#        - asset: assets/fonts/Poppins-Bold.ttf
#          weight: 700